project:
  title: "Dimension Reduction: a tutorial"

knitr:
  opts_chunk: 
    size: 'scriptsize'
    dev: 'pdf'
    fig.path: 'figs_quarto/'
    message: FALSE
    warning: false
    cache: true

bibliography: 
  - probabilistic_embedding.bib

csl: the-annals-of-statistics.csl

format: 
  beamer: 
    classoption: ['notheorems']
    fontfamily: libertinus
    fontsize: 11pt
    highlight-style: github
    monofont: Latin Modern Mono
    monofontoptions:
      - Scale=0.92
    linkcolor: miaps-blue-green-darker
    urlcolor: miaps-blue-green-darker
    colorlinks: true
    theme: default
    innertheme: circles
    outertheme: default
    fonttheme: professionalfonts
    fig-width: 12
    fig-height: 8
    fig-pos: 'htbp!'
    include-in-header: 
      - "color_theme_miaps.sty"
      - "beamer_theme.sty"
      - "preamble.sty"
      - "macros.sty"
