
## Poisson-lognormal PCA for the scRNA data set

```{r future-in, include=FALSE}
nb_cores <- 20
options(future.fork.enable = TRUE)
future::plan("multicore", workers = nb_cores)
```

```{r PLNPCA offset, cache=TRUE, warning=FALSE, message=FALSE, results='hide'}
PCA_scRNA <- PLNPCA(counts ~ 1 + offset(log(total_counts)), data = scRNA,
                    ranks = c(1, 2, seq(5, 40, 5)))
```

```{r future-out, include=FALSE}
future::plan("sequential")
```

:::: {.columns}

::: {.column width="80%"}

```{r PCA offset vizu cell-line, fig.width=6, fig.height=4, fig.align="center", echo=FALSE}
plot(PCA_scRNA)
myPCA_scRNA <- getBestModel(PCA_scRNA, "BIC")
```

:::

::::

## Poisson-lognormal PCA for the scRNA data set

:::: {.columns}

::: {.column width="80%"}

```{r PCA offset vizu tree, fig.width=6, fig.height=5, fig.align="center", echo=FALSE}
myPCA_scRNA %>% factoextra::fviz_pca_biplot(
  select.var = list(contrib = 40), addEllipses = TRUE, habillage = scRNA$cell_line,
  title = "Biplot (50 most contributing genes)"
  ) + scale_color_viridis_d()
```

:::

::::
