## Reinterpretation of PCA

#### PCA model

Let $\bV_q$ be a $p\times q$ matrix whose columns are of $q$ orthonormal vectors.

$$\Phi(\bx) = \bV_q^\top(\bx-\bmu)  = \bz, \quad \hat{\bx} = \tilde{\Phi}(\bz) = \bmu + \bV_q \bz.$$

\rsa Model with \emphase{Linear assumption + ortho-normality constraints}
 
#### PCA reconstruction error

\vspace{-.5cm}

$$
\minimize_{\bmu \in\Rset^p, \bV_q\in\mathcal{O}_{p,q}} \sum_{i=1}^n \left\| (\bx_i  - \bmu) - \bV\bV^\top ( \bx_i -\bmu)   \right\|^2 = \Bigg( \minimize_{\mathbf{F}_q\in\mathcal{M}_{n,q},\bV_q\in\mathcal{O}_{p,q} } \left\| \mathbf{X}^c - \mathbf{F_q V_q}^\top \right\|_F^2 \Bigg)
$$

#### Solution (explicit)
  
  - $\bmu$ is the empirical mean, $\bV_q$ eigenvectors of the empirical covariance
  - In practice: SVD of the centered matrix $\bX^c = \bU_q \bD_q \bV_q^\top = \mathbf{F}_q \bV_q^\top$ 

## Reconstruction error approach


Find maps $\Phi$ and $\tilde{\Phi}$ in a given family (e.g, linear, constraint on parameters, etc.), minimizing an error between $\bx$ and $\hat{\bx} = \tilde{\Phi}(\Phi(\bx))$

  - \emphase{Distance} between $\bX$ and $\hat{\bX}$, e.g, sum of squares:

\vspace{-.25cm}

$$
\epsilon^\text{SSQ}(\bX, \hat \bX ) = \left\| \bX - \hat \bX \right\|_F^2  = \sum_{i=1}^n \left\| \bx_i - \tilde{\Phi}(\Phi(\bx_i)) \right\|^2
$$

  - \emphase{Divergence} between distributions $\hat{p}_{\bX}$ and $\hat{p}_{\hat{\bX}}$ of $\bX_i$ and $\hat{\bX}_i$

\vspace{-.25cm}

$$
D_{\text{KL}}\left(\hat{p}_{\bX}, \hat{p}_{\hat{\bX}}\right) = - \sum_{i} \hat{p}_{\bX_i}  \log\left(\frac{\hat{p}_{\bX_i}}{\hat{p}_{\hat{\bX}_i}}\right)
$$

  - \emphase{Log-likelihood} of a parametric model $p_\theta$, with $\hat{\bX}=f(\theta)$:

\vspace{-.25cm}

$$
  - \log p_{\theta}(\bX) = - \sum_{i=1}^n \log p_{\btheta}(\bX_i)
$$

